<a href="https://colab.research.google.com/github/4060e059/2020AI/blob/main/20201007_%E4%B8%8A%E8%AA%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

In [31]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [32]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [33]:
import numpy as np
x = np.array([[1,2.0],[0,0],(1+1j,3.)])


In [34]:
import numpy as np
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
import numpy as np

In [37]:
# 亂數產生
data = np.random.randn(2, 3)
data

array([[ 0.59095107, -0.20474912,  0.08501233],
       [-0.76023048, -0.43407839, -2.31917465]])

In [38]:
#numpy.random.uniform介绍
#
data = np.random.uniform(2, 3)
data

2.206671090213824

In [39]:
#https://blog.csdn.net/u013920434/article/details/52507173
import numpy as np
 
s = np.random.uniform(0,1,10)
s

array([0.88921129, 0.44475874, 0.51420947, 0.10092161, 0.21944096,
       0.00637129, 0.13925133, 0.87951188, 0.66428779, 0.11174099])

In [40]:
sum(s)

3.9697053498947446

In [41]:
#https://github.com/MyDearGreatTeacher/AI_and_security_2020/blob/master/20201007.md
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [43]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
np.array(15)

array(15)

In [45]:
np.asarray(15)

array(15)

In [46]:
np.ones,(15)

(<function numpy.ones>, 15)

In [47]:
np.ones_like(15)

array(1)

In [48]:
np.zeros,(15)

(<function numpy.zeros>, 15)

In [49]:
np.zeros_like(15)

array(0)

In [50]:
np.empty,(15)

(<function numpy.empty>, 15)

In [51]:
np.empty_like(15)

array(52414416)

In [52]:
np.full,(15)

(<function numpy.full>, 15)

In [53]:
np.eye,(15)

(<function numpy.eye>, 15)

In [54]:
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [55]:
#Creat diagonal array

#array([2,0,0,0],
#   [0,1,0,0],
#   [0,0,4,0],
#   [0,0,0,6]])

ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [56]:
import numpy as np
x=np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [57]:
import numpy as np
y=np.arange(2,10).reshape(2,4)
y

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [58]:
ar=np.array([np.arange(1,6),np.arange(10,15)]);
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [59]:
import numpy as np
x=np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
ar=np.array([[2,3,4],[9,8,7],[11,12,13]]);
ar
#ar[1,2]
#ar[2,:]
#ar[:,1]

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [61]:
ar=2*np.arange(6);
ar
#ar[1:5:2]
#ar[1:6:2]
#ar[:4]
#ar[4:]
#ar[::3]
#ar[:3]=1;
#ar
#ar[2]:=np.ones(4)

array([ 0,  2,  4,  6,  8, 10])

In [62]:
#Reduction
ar=np.arange(1,5)
ar.prod()

24

In [63]:
ar=np.array([np.arange(1,6),np.arange(1,6)]);
ar
#np.prod(ar,axis=0)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [64]:
ar=range(1000)
%timeit[ar[i]**3for i in ar]
#for loop

1000 loops, best of 3: 378 µs per loop


In [65]:
ar=np.arange(1000)
%timeit ar**3
#vectorization

The slowest run took 13.97 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.57 µs per loop


In [66]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [68]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [69]:
x1 = np.arange(9.0).reshape((3,3))
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])